name: Simple Start Up
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Build my virtual OS
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: install plugin
      run: |
        pip install pytest pytest-cov
     - name: checkout my development codes
      uses: actions/checkout@v4
      with:
        repository: <change repo name>
    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: <secret repo>
        token: <secret repo token> 
        path: <path to locate content>
    - name: list current files
      run: |
        ls
        sudo mv <path of content>
    - name: Test Command
      if: always()
      run: |
        pytest -v -cov --junitxml=report.xml
