name: Simple Start Up
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Build my virtual OS
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
    - name: install plugin
      run: |
        pip install pytest pytest-cov
     - name: checkout my development codes
      uses: actions/checkout@v4
      with:
        repository: <change repo name>
    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: <secret repo>
        token: <secret repo token> 
        path: <path to locate content>
    - name: list current files
      run: |
        ls
        sudo mv <path of content>
    - name: Test Command
      if: always()
      run: |
        pytest -v -cov --junitxml=report.xml
    - if: ${{ failure() }}
      name: Create Issue on Failed workflow
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow Workflow name - `${{ github.workflow }}` failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
          assignees: <assignee acc name>
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"
